### PR TITLE
0856168 lab1

### PR DESCRIPTION
**Pull request by ex7763**
lab1 done

### CODE REVIEW

**Comment by csielee** [comment]
Hi! I am glad to see you create a pull request but your base branch is wrong (not `master`). The base branch should be your student id. Please edit your pull request.

**Comment by csielee** [comment]
Hi @ex7763 ! You can edit this pull request. Don't need to close it. Unless you want to change compare branch.

**Comment by ex7763** [comment]
我想說直接在開一個比較快，新的那個應該沒問題了

**Comment by csielee** [comment]
OK!

**Pull request closed without merging**
